version: '3.8'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server
    container_name: sql1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStr0ngPassw0rd!
    ports:
      - "1433:1433"
    volumes:
      - ./sql1_data:/var/opt/mssql
      - ./sql1_backups:/backups
    networks:
      - sql_network

  sql2:
    image: mcr.microsoft.com/mssql/server
    container_name: sql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStr0ngPassw0rd!
    ports:
      - "1434:1433"
    volumes:
      - ./sql2_data:/var/opt/mssql
      - ./sql2_backups:/backups
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

